line-length = 88
target-version = "py311"

[lint]
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort
  "B",  # flake8-bugbear
  "UP", # pyupgrade
  "N",  # pep8-naming
]
ignore = [
  # Тимчасово не вимагаємо повну типізацію анотацій
  "ANN",
  # Довжина рядка контролюється Black; не блокуємо лінтерами
  "E501",
  # Поступова міграція до `X | Y` в isinstance; не блокуємо збірку
  "UP038",
]

[lint.per-file-ignores]
"tests/**" = ["N", "E501"]
"app/main.py" = ["N815", "N805"]
"app/runtime.py" = ["N815", "N805"]
"app/settings.py" = ["N815", "N805"]
"app/smc_producer.py" = ["N815", "N805"]
"app/smc_state_manager.py" = ["N815", "N805"]
"app/" = ["N815", "N805"]
"UI/__init__.py" = ["N999"]
"core/contracts/__init__.py" = ["I001"]
"config/config.py" = ["N815", "N805"]
"smc_core/" = ["E501"]
"smc_liquidity/" = ["E501"]
"smc_structure/" = ["E501"]
"smc_zones/"= ["E501"]

[lint.isort]
known-first-party = [
  "app",
  "core",
  "config",
  "data",
  "UI",
  "smc_core",
  "smc_execution",
  "smc_structure",
  "smc_liquidity",
  "smc_zones",
  "tests"
]
combine-as-imports = true
